services:
  db:
    image: postgres
    container_name: devtiro
    environment:
      POSTGRES_USER: muchiri
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080