server:
  port: 8080

spring:
  application:
    name: devtiro-database
  datasource:
    url: jdbc:postgresql://localhost:5432/devtiro
    username: muchiri
    password: password
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#          ddl-auto: validate
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true